/**
 * Central workflow definitions for the Material Request → Goods Issue process.
 * Keeping every status and the legal transitions in one place makes the state
 * machine auditable and lets both backend guards and the frontend share the
 * same vocabulary (exposed via GET /api/meta).
 */

// --- Request header statuses ------------------------------------------------
const HEADER_STATUS = {
  DRAFT: 'Draft',
  SUBMITTED: 'Submitted',
  PENDING_MANAGER_APPROVAL: 'Pending Manager Approval',
  UNDER_REVIEW: 'Under Review',
  RETURNED_TO_REQUESTER: 'Returned to Requester',
  REJECTED: 'Rejected',
  APPROVED: 'Approved',
  APPROVED_PENDING_ERP: 'Approved - Pending ERP Processing',
  PENDING_ERP_RESERVATION: 'Pending ERP Reservation',
  ERP_RESERVATION_CREATED: 'ERP Reservation Created',
  MOVEMENT_TYPE_ASSIGNED: 'Movement Type Assigned',
  WAREHOUSE_ASSIGNED: 'Warehouse Assigned',
  PENDING_WAREHOUSE_ACTION: 'Pending Warehouse Action',
  PENDING_BIN_ASSIGNMENT: 'Pending Bin Location Assignment',
  LOCATION_ASSIGNED: 'Location Assigned',
  BATCH_ASSIGNED: 'Batch Assigned',
  PENDING_PICKER_ASSIGNMENT: 'Pending Picker Assignment',
  ASSIGNED_TO_PICKER: 'Assigned to Picker',
  PENDING_PICKER_ACCEPTANCE: 'Pending Picker Acceptance',
  REMINDER_SENT: 'Reminder Sent',
  ESCALATED_TO_SUPERVISOR: 'Escalated to Supervisor',
  ACCEPTED_BY_PICKER: 'Accepted by Picker',
  PICKING_IN_PROGRESS: 'Picking in Progress',
  PICKING_COMPLETED: 'Picking Completed',
  PARTIALLY_PICKED: 'Partially Picked',
  PENDING_ERP_GI: 'Pending ERP GI',
  GI_POSTED: 'GI Posted',
  COMPLETED: 'Completed',
  PARTIALLY_COMPLETED: 'Partially Completed',
  CLOSED_WITH_SHORTAGE: 'Closed with Shortage',
  CANCELLED: 'Cancelled',
  ON_HOLD: 'On Hold',
  ERP_ERROR: 'ERP Error',
  REVERSED: 'Reversed',
};

// --- Line item statuses -----------------------------------------------------
const LINE_STATUS = {
  DRAFT: 'Draft',
  PENDING_APPROVAL: 'Pending Approval',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  RETURNED: 'Returned',
  PENDING_ERP_RESERVATION: 'Pending ERP Reservation',
  RESERVED: 'Reserved',
  LOCATION_ASSIGNED: 'Location Assigned',
  BATCH_ASSIGNED: 'Batch Assigned',
  QR_VERIFICATION_REQUIRED: 'QR Verification Required',
  QR_VERIFIED: 'QR Verified',
  PICKING_PENDING: 'Picking Pending',
  PICKING_IN_PROGRESS: 'Picking in Progress',
  PICKED: 'Picked',
  PARTIALLY_PICKED: 'Partially Picked',
  SHORTAGE: 'Shortage',
  NOT_AVAILABLE: 'Not Available',
  EXPIRED: 'Expired',
  BLOCKED: 'Blocked',
  QUALITY_HOLD: 'Quality Hold',
  REPLACED: 'Replaced',
  PENDING_GI: 'Pending GI',
  GI_POSTED: 'GI Posted',
  REVERSED: 'Reversed',
  CANCELLED: 'Cancelled',
};

// --- Picking task statuses --------------------------------------------------
const TASK_STATUS = {
  CREATED: 'Created',
  ASSIGNED: 'Assigned to Picker',
  PENDING_ACCEPTANCE: 'Pending Picker Acceptance',
  REMINDER_SENT: 'Reminder Sent',
  ESCALATED: 'Escalated to Supervisor',
  ACCEPTED: 'Accepted by Picker',
  STARTED: 'Picking Started',
  IN_PROGRESS: 'Picking in Progress',
  COMPLETED: 'Picking Completed',
  PARTIALLY_COMPLETED: 'Partially Completed',
  RETURNED: 'Returned to Picker',
  CANCELLED: 'Cancelled',
  REASSIGNED: 'Reassigned',
};

// Legal header transitions (guards enforce these). Terminal states omitted.
const HEADER_TRANSITIONS = {
  [HEADER_STATUS.DRAFT]: [HEADER_STATUS.SUBMITTED, HEADER_STATUS.CANCELLED],
  [HEADER_STATUS.SUBMITTED]: [HEADER_STATUS.PENDING_MANAGER_APPROVAL, HEADER_STATUS.CANCELLED],
  [HEADER_STATUS.PENDING_MANAGER_APPROVAL]: [
    HEADER_STATUS.UNDER_REVIEW, HEADER_STATUS.APPROVED, HEADER_STATUS.REJECTED,
    HEADER_STATUS.RETURNED_TO_REQUESTER, HEADER_STATUS.ON_HOLD,
  ],
  [HEADER_STATUS.UNDER_REVIEW]: [
    HEADER_STATUS.APPROVED, HEADER_STATUS.REJECTED, HEADER_STATUS.RETURNED_TO_REQUESTER,
  ],
  [HEADER_STATUS.RETURNED_TO_REQUESTER]: [HEADER_STATUS.SUBMITTED, HEADER_STATUS.CANCELLED],
  [HEADER_STATUS.APPROVED]: [HEADER_STATUS.APPROVED_PENDING_ERP],
  [HEADER_STATUS.APPROVED_PENDING_ERP]: [HEADER_STATUS.PENDING_ERP_RESERVATION, HEADER_STATUS.ERP_RESERVATION_CREATED],
  [HEADER_STATUS.PENDING_ERP_RESERVATION]: [HEADER_STATUS.ERP_RESERVATION_CREATED, HEADER_STATUS.ON_HOLD],
  [HEADER_STATUS.ERP_RESERVATION_CREATED]: [HEADER_STATUS.MOVEMENT_TYPE_ASSIGNED],
  [HEADER_STATUS.MOVEMENT_TYPE_ASSIGNED]: [HEADER_STATUS.WAREHOUSE_ASSIGNED],
  [HEADER_STATUS.WAREHOUSE_ASSIGNED]: [HEADER_STATUS.PENDING_WAREHOUSE_ACTION, HEADER_STATUS.PENDING_BIN_ASSIGNMENT],
  [HEADER_STATUS.PENDING_WAREHOUSE_ACTION]: [HEADER_STATUS.PENDING_BIN_ASSIGNMENT],
  [HEADER_STATUS.PENDING_BIN_ASSIGNMENT]: [HEADER_STATUS.LOCATION_ASSIGNED],
  [HEADER_STATUS.LOCATION_ASSIGNED]: [HEADER_STATUS.BATCH_ASSIGNED, HEADER_STATUS.PENDING_PICKER_ASSIGNMENT],
  [HEADER_STATUS.BATCH_ASSIGNED]: [HEADER_STATUS.PENDING_PICKER_ASSIGNMENT],
  // LOCATION_ASSIGNED is allowed backwards so the supervisor can safely
  // re-run allocation (e.g. new stock received) before a picker is assigned.
  [HEADER_STATUS.PENDING_PICKER_ASSIGNMENT]: [HEADER_STATUS.ASSIGNED_TO_PICKER, HEADER_STATUS.LOCATION_ASSIGNED],
  [HEADER_STATUS.ASSIGNED_TO_PICKER]: [HEADER_STATUS.PENDING_PICKER_ACCEPTANCE],
  [HEADER_STATUS.PENDING_PICKER_ACCEPTANCE]: [
    HEADER_STATUS.REMINDER_SENT, HEADER_STATUS.ESCALATED_TO_SUPERVISOR, HEADER_STATUS.ACCEPTED_BY_PICKER,
  ],
  [HEADER_STATUS.REMINDER_SENT]: [
    HEADER_STATUS.ESCALATED_TO_SUPERVISOR, HEADER_STATUS.ACCEPTED_BY_PICKER, HEADER_STATUS.REMINDER_SENT,
  ],
  [HEADER_STATUS.ESCALATED_TO_SUPERVISOR]: [HEADER_STATUS.ASSIGNED_TO_PICKER, HEADER_STATUS.ACCEPTED_BY_PICKER],
  [HEADER_STATUS.ACCEPTED_BY_PICKER]: [HEADER_STATUS.PICKING_IN_PROGRESS],
  [HEADER_STATUS.PICKING_IN_PROGRESS]: [HEADER_STATUS.PICKING_COMPLETED, HEADER_STATUS.PARTIALLY_PICKED],
  [HEADER_STATUS.PICKING_COMPLETED]: [HEADER_STATUS.PENDING_ERP_GI],
  [HEADER_STATUS.PARTIALLY_PICKED]: [HEADER_STATUS.PENDING_ERP_GI],
  // PICKING_IN_PROGRESS is allowed backwards from the GI stage so the GI
  // operator can return the task to the picker for a re-pick.
  [HEADER_STATUS.PENDING_ERP_GI]: [
    HEADER_STATUS.GI_POSTED, HEADER_STATUS.ERP_ERROR, HEADER_STATUS.PICKING_IN_PROGRESS,
  ],
  [HEADER_STATUS.GI_POSTED]: [
    HEADER_STATUS.COMPLETED, HEADER_STATUS.PARTIALLY_COMPLETED, HEADER_STATUS.CLOSED_WITH_SHORTAGE,
  ],
  // A posted goods issue can be reversed (movement-type reversal) which returns
  // the issued stock to its batches and closes the request as Reversed.
  [HEADER_STATUS.COMPLETED]: [HEADER_STATUS.REVERSED],
  [HEADER_STATUS.PARTIALLY_COMPLETED]: [HEADER_STATUS.REVERSED],
  [HEADER_STATUS.CLOSED_WITH_SHORTAGE]: [HEADER_STATUS.REVERSED],
  [HEADER_STATUS.ERP_ERROR]: [
    HEADER_STATUS.PENDING_ERP_GI, HEADER_STATUS.ON_HOLD, HEADER_STATUS.PICKING_IN_PROGRESS,
  ],
  [HEADER_STATUS.ON_HOLD]: [
    HEADER_STATUS.PENDING_ERP_RESERVATION, HEADER_STATUS.PENDING_WAREHOUSE_ACTION, HEADER_STATUS.CANCELLED,
  ],
};

/** Returns true if a header may move from -> to. On-hold/cancel are broadly allowed. */
function canTransition(from, to) {
  if (from === to) return true;
  if (to === HEADER_STATUS.CANCELLED || to === HEADER_STATUS.ON_HOLD) return true;
  const allowed = HEADER_TRANSITIONS[from] || [];
  return allowed.includes(to);
}

module.exports = {
  HEADER_STATUS,
  LINE_STATUS,
  TASK_STATUS,
  HEADER_TRANSITIONS,
  canTransition,
};
